# Generated by Django 6.0.3 on 2026-03-09 10:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the contract (UUID for API security).', primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='The uploaded PDF or image of the financial document.', upload_to='contracts/%Y/%m/%d/')),
                ('original_filename', models.CharField(blank=True, help_text='The original name of the uploaded file.', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Current processing status of the contract.', max_length=20)),
                ('raw_llm_response', models.JSONField(blank=True, help_text='The raw JSON response from the LLM. Stored as a safety measure so parsing logic can be changed without re-running expensive LLM calls.', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Hidden Fees, High-Interest Triggers, Late Payment Penalties', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief explanation of what this risk category covers.')),
            ],
            options={
                'verbose_name': 'Risk Category',
                'verbose_name_plural': 'Risk Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContractSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(help_text='Risk rating from 0 (safe) to 100 (extremely risky).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('executive_summary', models.TextField(help_text="A 2-3 sentence TL;DR of the entire document's risk profile.")),
                ('contract', models.OneToOneField(help_text='The contract this summary belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='core_logic.contract')),
            ],
            options={
                'verbose_name': 'Contract Summary',
                'verbose_name_plural': 'Contract Summaries',
            },
        ),
        migrations.CreateModel(
            name='RiskFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField(help_text='The exact quote from the document — crucial for the highlighting feature.')),
                ('risk_explanation', models.TextField(help_text='Why the AI considers this clause predatory or risky.')),
                ('severity_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], db_index=True, default='MEDIUM', help_text="Drives the 'Bright Red' UI intensity (Low / Medium / High).", max_length=10)),
                ('suggested_alternative', models.TextField(blank=True, help_text="What a 'fair' version of this clause would look like (optional).")),
                ('category', models.ForeignKey(blank=True, help_text='The type of risk (e.g., Hidden Fees, Arbitration).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='core_logic.riskcategory')),
                ('contract', models.ForeignKey(help_text='The contract this finding belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='risk_findings', to='core_logic.contract')),
            ],
            options={
                'verbose_name': 'Risk Finding',
                'verbose_name_plural': 'Risk Findings',
                'ordering': ['-severity_level'],
            },
        ),
    ]
