# Generated by Django 6.0.3 on 2026-03-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_logic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='file',
            field=models.FileField(blank=True, help_text='The uploaded PDF or image. Physically deleted immediately after processing for privacy.', null=True, upload_to='contracts/%Y/%m/%d/'),
        ),
    ]
